services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: ansible.Dockerfile
    volumes:
      - ./config/keys:/keys
      - ./config/files:/files
      - ./config/files/hosts:/etc/ansible/hosts
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      #- ANSIBLE_CALLBACK_WHITELIST=json
      - ANSIBLE_STDOUT_CALLBACK=logstash
    #command: ["sleep", "inf"]
    #command: ["ansible-playbook", "/files/playbook.yaml"]
    command: ["ansible-playbook", "/files/centos-lamp-playbook.yaml"]
    #command: ansible-doc -t callback -l
    logging:
      driver: syslog
      options:
        tag: docker-ansible