---
- name: Install packages
  hosts: artemis

  tasks:
  - name: Install git, httpd, mysql
    become: yes
    ansible.builtin.yum:
      name:
      - httpd
      - git
      - mysql-server
      state: latest

  - name: Enable and start httpd service
    become: yes
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started

  - name: Enable and start mysql services
    become: yes
    ansible.builtin.service:
      name: mysqld
      enabled: true
      state: started

  - name: Add httpd port
    become: yes
    ansible.posix.firewalld:
      zone: public
      service: http
      state: enabled
      permanent: yes

  - name: Refresh firewall-cmd
    become: yes
    ansible.posix.firewalld:
      zone: public
      service: http
      state: enabled
      permanent: yes
      immediate: true

  - name: update
    become: yes
    ansible.builtin.yum:
      name: "*"
      state: latest

  - name: xfs_mkfile
    become: no
    shell: xfs_mkfile 495M sample.rnd

  - name: get sample.rnd size
    become: no
    stat:
      path: sample.rnd
    register: file_info
    
  - name: Display file size
    debug:
      var: file_info.stat

  - name: delete sample.rnd
    become: no
    command: rm -rf sample.rnd 