---
- name: Install and update rsyslog and rsyslog-omhttp
  hosts: artemis

  tasks:
  - name: Install git and epel
    become: yes
    ansible.builtin.yum:
      name:
      - git
      - epel-release
      state: latest

  - name: Add rsyslog repository
    become: yes
    ansible.builtin.yum_repository:
      name: rsyslog_v8
      description: EPEL YUM repo
      baseurl: 'http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch'
      enabled: true
      gpgcheck: false
      gpgkey: 'https://rpms.adiscon.com/RPM-GPG-KEY-Adiscon'
      protect: true
    environment:
        distro: $(sed -n 's/^distroverpkg=//p' /etc/yum.conf)
        releasever: $(rpm -q --qf "%{version}" -f /etc/$distro)
        basearch: $(rpm -q --qf "%{arch}" -f /etc/$distro)

  - name: Update
    become: yes
    ansible.builtin.yum:
      update_only: true

  - name: Install rsyslog-omhttp
    become: yes
    ansible.builtin.dnf:
      name: rsyslog-omhttp
      state: latest

- name: Write rsyslog conf files
  hosts: artemis

  tasks:
  - name: Git clone rsyslog-ekl
    ansible.builtin.git:
      repo: 'https://github.com/PedroJesus044/rsyslog-ekl.git'
      dest: rsyslog-ekl
      update: true

  - name: Ensure rsyslog.d directory is empty
    become: yes
    ansible.builtin.command: sudo rm -rf /etc/rsyslog.d/*

  - name: Copy rsyslog files
    become: yes
    ansible.builtin.command: cp -rf rsyslog-ekl/elastic.rsyslog.cloud.conf /etc/rsyslog.d/

  - name: Restart rsyslog
    become: yes
    ansible.builtin.service:
      name: rsyslog
      state: restarted

  - name: Check rsyslog health
    become: yes
    ansible.builtin.service:
      name: rsyslog
      state: started